---
- name: SSH - Disable password authentication for root.
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?RootLoginAllowed'
    line: 'PermitRootLogin no'
    backup: true
    validate: 'sshd -t -f %s'

- name: SSH - Restart the SSH daemon.
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: UFW - Allow SSH connections.
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Enable and deny by default.
  community.general.ufw:
    state: enabled
    default: deny

- name: PAM - Set the default umask to 0027.
  community.general.pamd:
    name: common-session
    state: updated
    type: session
    control: optional
    module_path: pam_umask.so
    module_arguments: umask=0027
    backup: true

