services:
  minecraft-server-forge:
    image: itzg/minecraft-server
    container_name: minecraft-server-neoforge
    restart: unless-stopped
    environment:
      EULA: TRUE
      DIFFICULTY: hard
      ENABLE_ROLLING_LOGS: TRUE
      LOG_TIMESTAMP: TRUE
      MEMORY: 8G
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_FORCE_SYNCHRONIZE: TRUE
      MODRINTH_MODPACK: $PROJECT_ID
      MODRINTH_VERSION: $VERSION_ID
      MOTD: $MOTD
      OPS: $OPERATORS
      SNOOPER_ENABLED: FALSE
      USE_AIKAR_FLAGS: TRUE
      VERSION: 1.21.1
    volumes:
      - "/opt/minecraft/minecraft-server-neoforge:/data"

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TZ: Etc/UTC
      TUNNEL_TOKEN: $CLOUDFLARE_TOKEN
