services:
  minecraft-server-forge:
    image: itzg/minecraft-server
    container_name: minecraft-server-forge
    restart: unless-stopped
    environment:
      MEMORY: 12G
      USE_AIKAR_FLAGS: TRUE
      ENABLE_ROLLING_LOGS: TRUE
      LOG_TIMESTAMP: TRUE
      EULA: TRUE
      DIFFICULTY: hard
      LEVEL_TYPE: bclib:betterx
      MOTD: $FORGE_MOTD
      OPS: $OPS
      MODPACK_PLATFORM: MODRINTH
      MODRINTH_VERSION: $VERSION_ID
      MODRINTH_FORCE_SYNCHRONIZE: TRUE
    volumes:
      - "/opt/minecraft/minecraft-server-forge:/data"

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TZ: Etc/UTC
      TUNNEL_TOKEN: $TOKEN
