---
- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Install the listed package(s), ignoring install_recommends.
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - fail2ban
      - ufw
    install_recommends: no

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists and reboot_required_file is defined

- name: Remove dependencies that are no longer required and purge their configuration files.
  ansible.builtin.apt:
    autoremove: yes
    purge: true

- name: Remove package files that can no longer be downloaded from the cache.
  ansible.builtin.apt:
    autoclean: yes
