---
- name: Perform a dist-upgrade.
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 1
  tags: remote # If being performed locally, this task can be skipped as it will need to be done to install Ansible anyway.

- name: Do not automatically start service(s) after installation
  ansible.builtin.copy:
    dest: /usr/sbin/policy-rc.d
    content: 'exit 101'
    mode: '755'

- name: Install the listed package(s), ignoring install_recommends.
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - ufw
    install_recommends: no

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if a reboot is required).
  ansible.builtin.reboot:
  when: reboot_required_file is defined and reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required and purge their configuration files.
  ansible.builtin.apt:
    autoremove: yes
    purge: true

- name: Remove package files that can no longer be downloaded from the cache.
  ansible.builtin.apt:
    autoclean: yes
